### PR TITLE
Use requirements.txt for Gubernator dependencies

### PR DESCRIPTION
**Pull request by stevekuznetsov**
Deploying Gubernator using a custom runtime on Google App Engine or
    deploying it without Google App Engine entirely should be possible. To
    enable these efforts, the dependency requirements for the applciation
    should be listed in the standard `requirements.txt` manifest instead of
    the Google App Engine-specific YAML.
    
    Signed-off-by: Steve Kuznetsov <skuznets@redhat.com>

### CODE REVIEW

**Comment by kargakis** [comment]
Should go upstream first and then pulled in here. Unless it is not accepted upstream...

**Comment by kargakis** [comment]
Upstream this was merged with a difference: https://github.com/kubernetes/test-infra/pull/3483

I want to pull in latest and will need to force-push but let me know if the diff will be an issue first..

**Comment by stevekuznetsov** [comment]
Nope, force-push over it -- I just wanted my BuildConfig to work while I was testing

**Comment by kargakis** [comment]
Ok, thanks!

**Pull request merged**
