### PR TITLE
Redesign Prow Status dashboard

### PR DESCRIPTION
**Pull request by jhadvig**
Screen:
download 2

@stevekuznetsov @kargakis PTAL

### CODE REVIEW

**Comment by kargakis** [comment]
Cool! I would suggest having a separate directory with our static content
so we can avoid conflicts on rebases.

On Wednesday, August 16, 2017, Jakub Hadvig <notifications@github.com>
wrote:
> Screen:
> <
https://ci4.googleusercontent.com/proxy/14G_XqpiEXAeMrcwnyvt_5TlktkKcVeaRibZ4uIZY7Pl6A19KPvD0Wwr9wbTsSfWWOXWsWBtI7M0SJtdW1kw0k1V4CrpYrmMi8TYgrgHzQymvzDzslIjPb7PsrZgZFza3ou9JBM6Lw0QHhxgLwy1Ld1KAakUbAbu6g=s0-d-e1-ft#https://user-images.githubusercontent.com/1668218/29361424-e077698c-8287-11e7-80ca-9eadcdec5fd7.png
>
>
> @stevekuznetsov @kargakis PTAL
>
> ________________________________
>
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/openshift/test-infra/pull/15
>
> Commit Summary
>
> Redesign Prow Status dashboard
>
> File Changes
>
> M prow/cmd/deck/static/index.html (1)
> A prow/cmd/deck/static/logo.png (0)
> M prow/cmd/deck/static/style.css (25)
>
> Patch Links:
>
> https://github.com/openshift/test-infra/pull/15.patch
> https://github.com/openshift/test-infra/pull/15.diff
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.<
https://ci5.googleusercontent.com/proxy/h_mzgLllp7S17k47Vt1yRkYxZ3CcyWOMKjDnP0cNhADbFoM9FIKIeOxdZxiCVKElDmsCMct7h3nswNrEwTY_ByCpFD-pB7LjXqy8zbABUBzaI-oGaGiik8lGN74y6IUdB67bRsQxV0MTHfOtf-GRsf4VS01Oog=s0-d-e1-ft#https://github.com/notifications/beacon/ADuFf0i7l_NTW7LTxFrMxwtSq0zComGiks5sYtRAgaJpZM4O4x_m.gif>

**Comment by kargakis** [comment]
The prow and deck BCs would need to change to point to the new static
directory in
https://github.com/openshift/release/blob/master/cluster/ci/config/prow/prow_images.yaml

On Wednesday, August 16, 2017, Michail Kargakis <mkargaki@redhat.com> wrote:
> Cool! I would suggest having a separate directory with our static content
so we can avoid conflicts on rebases.
>
> On Wednesday, August 16, 2017, Jakub Hadvig <notifications@github.com>
wrote:
>> Screen:
>> <
https://ci4.googleusercontent.com/proxy/14G_XqpiEXAeMrcwnyvt_5TlktkKcVeaRibZ4uIZY7Pl6A19KPvD0Wwr9wbTsSfWWOXWsWBtI7M0SJtdW1kw0k1V4CrpYrmMi8TYgrgHzQymvzDzslIjPb7PsrZgZFza3ou9JBM6Lw0QHhxgLwy1Ld1KAakUbAbu6g=s0-d-e1-ft#https://user-images.githubusercontent.com/1668218/29361424-e077698c-8287-11e7-80ca-9eadcdec5fd7.png
>
>>
>> @stevekuznetsov @kargakis PTAL
>>
>> ________________________________
>>
>> You can view, comment on, or merge this pull request online at:
>>
>>   https://github.com/openshift/test-infra/pull/15
>>
>> Commit Summary
>>
>> Redesign Prow Status dashboard
>>
>> File Changes
>>
>> M prow/cmd/deck/static/index.html (1)
>> A prow/cmd/deck/static/logo.png (0)
>> M prow/cmd/deck/static/style.css (25)
>>
>> Patch Links:
>>
>> https://github.com/openshift/test-infra/pull/15.patch
>> https://github.com/openshift/test-infra/pull/15.diff
>>
>> —
>> You are receiving this because you were mentioned.
>> Reply to this email directly, view it on GitHub, or mute the thread.<
https://ci5.googleusercontent.com/proxy/h_mzgLllp7S17k47Vt1yRkYxZ3CcyWOMKjDnP0cNhADbFoM9FIKIeOxdZxiCVKElDmsCMct7h3nswNrEwTY_ByCpFD-pB7LjXqy8zbABUBzaI-oGaGiik8lGN74y6IUdB67bRsQxV0MTHfOtf-GRsf4VS01Oog=s0-d-e1-ft#https://github.com/notifications/beacon/ADuFf0i7l_NTW7LTxFrMxwtSq0zComGiks5sYtRAgaJpZM4O4x_m.gif>

**Comment by jhadvig** [comment]
So do we need to revert https://github.com/openshift/test-infra/pull/14 ?

**Comment by stevekuznetsov** [comment]
@jhadvig sure, revert and update

**Comment by jhadvig** [comment]
Closing this PR in favor of https://github.com/openshift/test-infra/pull/17

**Pull request closed without merging**
