### PR TITLE
Apply styling changes from sgoodwin

### PR DESCRIPTION
**Pull request by stevekuznetsov**
Signed-off-by: Steve Kuznetsov <skuznets@redhat.com>

/cc @sg00dwin live here https://v20170913-1055b3e-dot-github-dot-openshift-gce-devel.appspot.com

### CODE REVIEW

**Comment by sg00dwin** [comment]
@stevekuznetsov I'm getting a 404 for that link.

**Comment by stevekuznetsov** [comment]
@sg00dwin try again at https://v20170913-1055b3e-dot-openshift-gce-devel.appspot.com/ ?

**Comment by stevekuznetsov** [comment]
@sg00dwin did you get a chance to look this over? I'd like to close this out

**Comment by sg00dwin** [comment]
@stevekuznetsov  I will today and let you know if I see anything.

**Comment by smarterclayton** [comment]
I'm sad, I want to merge fixes too....

**Comment by sg00dwin** [comment]
I had this pr https://github.com/stevekuznetsov/test-infra/pull/1 that prettified the Origin gubernator. Then learned steve wants to push upstream, so I'm gathering the pieces to go upsteam and from the Origin specific branding.  ...soon that frown will be turned upside down.

**Comment by stevekuznetsov** [comment]
Are you OK if we merge this as-is and you can layer on top later?

We will attempt a broken-out config like in https://github.com/openshift/test-infra/pull/33/files

/cc @jhadvig

**Comment by sg00dwin** [comment]
@stevekuznetsov I'm updating my pr now with base changes for upstream and customizations for our branding

**Comment by sg00dwin** [comment]
@stevekuznetsov https://github.com/stevekuznetsov/test-infra/pull/1#issuecomment-332254262

**Comment by smarterclayton** [comment]
Sad face, want to merge my changes

**Comment by stevekuznetsov** [comment]
Clayton -- if you want to do the reviews and merges, I trust you will do it well. I've had no time for this over CRI-O business the last two weeks. My apologies.

**Comment by stevekuznetsov** [comment]
@sg00dwin @smarterclayton deployed here https://v20171005-90eaa9b-dot-openshift-gce-devel.appspot.com

overview page doesn't seem to have picked up the changes

**Comment by stevekuznetsov** [comment]
Pushed the wrong button, live here: https://v20171005-6d7e512-dot-openshift-gce-devel.appspot.com

overview page looks good

**Comment by stevekuznetsov** [comment]
Is the header supposed to be blue? Blue links on blue header is hard to read

**Comment by stevekuznetsov** [comment]
screenshot from 2017-10-05 10-40-03

**Comment by smarterclayton** [comment]
That blue is terrible....

**Comment by smarterclayton** [comment]
This doesn't have my changes to put the job name in the sub line

**Comment by smarterclayton** [comment]
Specifically
[image: text]

Should be "REPO PR #" then newline "JOB JOB#"

**Comment by stevekuznetsov** [comment]
@sg00dwin you should be able to push to this branch to update

**Comment by stevekuznetsov** [comment]
or just make your own branch and use that, we can close this PR

**Comment by stevekuznetsov** [comment]
@sg00dwin deployed newest at https://v20171005-be78726-dot-openshift-gce-devel.appspot.com

**Comment by smarterclayton** [comment]
The version referenced here doesn't have my changes to make the header be:

```
REPO_NAME # PR_NUMBER
job_name # job_number
```

**Comment by smarterclayton** [comment]
If this isn't going to be ready I want to merge the other PR

**Comment by sg00dwin** [comment]
@smarterclayton 
Do your header changes look ok? Also added bg color for the 'artifacts' and 'build log' links.
https://v20171106-8b587910-dirty-dot-openshift-gce-devel.appspot.com/build/origin-ci-test/logs/test_branch_origin_check/1968/

If so I have a pr open for these updates. https://github.com/openshift/test-infra/pull/57

**Comment by sg00dwin** [comment]
@stevekuznetsov this is good to merge

**Comment by stevekuznetsov** [comment]
@sg00dwin can you promote your latest code to prod for the deployment?

**Pull request merged**
