### PR TITLE
Rebrand gubernator

### PR DESCRIPTION
**Pull request by jhadvig**
Screens:

@stevekuznetsov @jupierce PTAL

### CODE REVIEW

**Comment by kargakis** [comment]
Nice

We need to talk next week about how are we going to approach carrying long-term changes like branding. Does it make sense to move the discussion upstream?

**Comment by jupierce** [comment]
Awesome! Only area of concern would be the blue hyperlink on red background (e.g. "PR Dashboard" in the first image). Not a high contrast pairing.

**Comment by stevekuznetsov** [comment]
Can we tone down the saturation on the red background or make it a darker shade? It is a little overwhelming right now

**Comment by jhadvig** [comment]
@kargakis sure lets talk. 

@stevekuznetsov @jupierce I;ve tone down the red background so the links are more contrast.
Screen:

download 3

**Pull request merged**
