### PR TITLE
Rebrand submit queue

### PR DESCRIPTION
**Pull request by jhadvig**
Rebranding our submit queue.
Screens:

download

download 1

@kargakis @jupierce @stevekuznetsov PTAL

### CODE REVIEW

**Comment by stevekuznetsov** [comment]
@jhadvig this looks amazing@

**Comment by stevekuznetsov** [comment]
I think we'll need a submitqueue redeployment to get this, though, so I'll wait untl the weekend

**Comment by kargakis** [comment]
@stevekuznetsov can you do a rebase before redeploying?

**Comment by stevekuznetsov** [comment]
Yep

**Pull request merged**
