### PR TITLE
Add branding customization as an extension

### PR DESCRIPTION
**Pull request by jhadvig**
Added branding as an extension and removing old branding static folder

@kargakis @stevekuznetsov PTAL

### CODE REVIEW

**Comment by kargakis** [comment]
I am still in favor of having just the colors and logo being configurable but this 

/lgtm

**Comment by jhadvig** [comment]
For this kind of static pages, there are si no sane/easy way how to have a config file that would describe eg. colors or logo path. This is the easiest way afaik

**Comment by stevekuznetsov** [comment]
@jhadvig this looks awesome!

**Comment by jhadvig** [comment]
@stevekuznetsov can we merge this ?

**Pull request merged**
